// frontend_old/components/Navbar.vue
<template>
  <header class="w-full py-4 border-b border-ink-200 bg-ink-400">
    <nav class="flex items-center justify-center flex-wrap">
      <nuxt-link to="/" class="flex items-center text-gray-700 font-bold">
        <img src="~/static/gfi-logo-white.svg" alt="Good First Issue" class="h-12" />
      </nuxt-link>
      <span v-if="activeTag" class="text-2xl cursor-pointer">
        <span class="font-normal ml-2 mr-1 text-slate">/</span>
        <span class="font-semibold text-juniper">{{ activeTag.language }}</span>
      </span>
    </nav>
  </header>
</template>

<script>
import { find } from 'lodash'
import Tags from '~/data/tags.json'

export default {
  props: {
    tag: {
      type: Object,
      required: true
    }
  },
  computed: {
    activeTag: function () {
      return find(Tags, { slug: this.$route.params.slug })
    }
  }
}
</script>

// components/Navbar.tsx
import React from 'react'
import Link from 'next/link'
import Image from 'next/image'
import { Tag } from '../Types'

type NavbarProps = {
  tags: Tag[]
}

export const Navbar = ({ tags }: NavbarProps) => {
  const thisRoute = 'none'
  const activeTag = tags.find((t) => t.language == thisRoute)

  return (
    <header className="w-full py-4 border-b border-ink-200 bg-ink-400">
      <nav className="flex items-center justify-center flex-wrap">
        <Link href="/" className="flex items-center text-gray-700 font-bold">
          <Image
            src="/gfi-logo.svg"
            alt="Good First Issue"
            className="h-12"
            width={300}
            height={100}
          />
        </Link>
        {activeTag ? (
          <span className="text-2xl cursor-pointer">
            <span className="font-normal ml-2 mr-1 text-slate">/</span>
            <span className="font-semibold text-juniper">{activeTag.language}</span>
          </span>
        ) : null}
      </nav>
    </header>
  )
}
